name: "bon-game"

services:
  backend:
    container_name: "bon-game-backend"
    build: ../../../backend
    command: "air -c .air.toml"
    volumes:
      - "../../../backend:/app"
    ports:
      - "3132:3132"
    depends_on:
      - redis

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  redis:
    image: redis:7-alpine
    container_name: "bon-game-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
